### PR TITLE
Make history abstract

### PR DESCRIPTION
**Pull request by chaabaj**

### CODE REVIEW

**Comment by chaabaj** [comment]
It remove all dependencies with DOM. So it can be used in react-native, server side rendering, testing without bringing a DOM API or browser

**Comment by ben-x9** [comment]
Let's have a default for the history parameter that uses the DOM history API

**Comment by chaabaj** [comment]
Ok

**Comment by chaabaj** [comment]
Updated. Select correct history implementation by checking environment

**Pull request merged**
