### PR TITLE
Add task dispatcher

### PR DESCRIPTION
**Pull request by chaabaj**
Adding task dispatcher and application hooks.

### CODE REVIEW

**Comment by chaabaj** [comment]
Found a bug i will close for now fix and open after

**Comment by chaabaj** [comment]
OK now it's fine

**Comment by ben-x9** [comment]
It looks like we still don't set the Redux action name based on the function name?

**Comment by chaabaj** [comment]
Yes because it doesn't work with curried function so it's not really reliable.

**Comment by ben-x9** [comment]
Maybe we can prefix with something so it still works with curried functions?

Anyway this is good enough for now, LGTM

**Pull request merged**
